### ISSUE TITLE
git custom aliases should override base aliases

### ISSUE THREAD

**Issue by chendrix** [pivotal-sprout/sprout-git#19]
[`aliases = node['sprout']['git']['aliases'] + node['sprout']['git']['base_aliases']`](https://github.com/pivotal-sprout/sprout-git/blob/master/recipes/aliases.rb#L3)

should probably reverse those, so that the custom git aliases override the base aliases

**Comment by aramprice** [comment]
I think this will be addressed by #27 since `global_config` data is a hash, keyed by the alias name. If we merge custom and base hashes in the correct direction, users settings will win

**Comment by codeword** [comment]
at this point I think @chendrix change would actually fix the override issue.  When the git aliases recipe was change to use the `global_config` lwrp it lost the "only_if" clause causing later aliases to override earlier ones.  I think we can write an integration tests that keep the intent of the feature tested without caring about the specific implementation.  I am going to take a crack at the integration test that will expose the bug.  I don't really care whether we fix it with @aramprice's approach of switching to use a more generic `config` recipe or simply reverse the order of the alias loading suggested by @chendrix

**Comment by michaelxupiv** [comment]
+1. We are seeing the same issue with base_aliases overriding our custom ones. Our current hack-around fix is to name our custom aliases as `base_aliases`. Hope this gets fixed soon :)

**Comment by aramprice** [comment]
Going to archive this repo, closing.
