### ISSUE TITLE
Remove `sprout-git::aliases` in favor of the more generic `::global_config`

### ISSUE THREAD

**Issue by aramprice** [pivotal-sprout/sprout-git#27]

**Comment by aramprice** [comment]
If we join the `global_config` settings with user provided preferences we should merge the hashes in the direction which favors users' input (see: #19)

**Comment by aramprice** [comment]
ping @wendorf

**Comment by wendorf** [comment]
This is too big of a breaking change for many users, and aliases are more or less the only git config variables that are wildcarded (e.g. `alias.*`) so it doesn't feel wrong to treat them specially.

There may be a deprecation path forward, but I don't know exactly what that would look like. Thoughts?

**Comment by aramprice** [comment]
I'm thinking that longer term it would be nice to have a general `sprout-git::config` recipe.

I think it would be possible for us to have some/reasonable defaults in: `node.default['sprout']['git']['config']` as a `'config.name' => 'config value'` hash so that users can override config settings (aliases in particular) which they don't want.

A possible future enhancement for `node.default['sprout']['git']

```ruby
'config.name' => {'value' => 'config value', 'scope' => 'system-OR-global'}
```
