### ISSUE TITLE
Don't add git-secrets hook by default

### ISSUE THREAD

**Issue by wendorf** [pivotal-sprout/sprout-git#36]
I think this is pretty unexpected behavior for most people who use Sprout. A user who merges upstream will find that commits that used to work for private repositories stop working, and may have difficulty understanding what happened.

@aramprice Thoughts?

**Comment by aramprice** [comment]
I agree. It wasn't my intention that this be added to the `default` recipe. We've been telling teams that need the `git secrets` functionality to add `sprout-git::git_secrets` to their `soloistrc`
