### ISSUE TITLE
git-hooks attributes aren't documented in the README.md

### ISSUE THREAD

**Issue by wendorf** [pivotal-sprout/sprout-git#39]

**Comment by aramprice** [comment]
Noted. I think probably the list of hooks should probably not be configurable but `global_dir` could be valuable.

**Comment by aramprice** [comment]
Closing as `git_hooks` recipe has been [deprecated](https://github.com/pivotal-sprout/sprout-git/commit/62f1db52fbda647e732f8fa84cc518e0afbabb91).
